server:
  port: 8080

spring:
  datasource:
    continue-on-error: true
    driver-class-name: org.mariadb.jdbc.Driver
    password: admin
    username: sqladmin
    test-on-borrow: true
    url: jdbc:mariadb://localhost:3306/hiber
    validation-query: SELECT 1
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    format-sql: true
    use_sql_comments: true